'use client'
import {useEffect,useState} from 'react'
import {Elements,PaymentElement,useElements,useStripe} from '@stripe/react-stripe-js'
import {loadStripe} from '@stripe/stripe-js'
import type {HttpTypes} from '@medusajs/types'
import {getPrintCart,medusa} from '@/lib/medusa'
const stripePromise=process.env.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY?loadStripe(process.env.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY):null
function Pay({cart,onComplete}:{cart:HttpTypes.StoreCart;onComplete:(id:string)=>void}){
 const stripe=useStripe(),elements=useElements();const [error,setError]=useState(''),[busy,setBusy]=useState(false)
 async function pay(){if(!stripe||!elements)return;setBusy(true);try{const result=await stripe.confirmPayment({elements,confirmParams:{return_url:window.location.href},redirect:'if_required'});if(result.error)throw Error(result.error.message);const completed=await medusa.store.cart.complete(cart.id);if(completed.type!=='order')throw Error('Payment received; order processing is incomplete. Please contact us before paying again.');localStorage.removeItem('lp_medusa_cart');onComplete(completed.order.id)}catch(e){setError(e instanceof Error?e.message:'Payment unavailable')}finally{setBusy(false)}}
 return <div className="space-y-4"><PaymentElement/>{error&&<p role="alert">{error}</p>}<button disabled={busy||!stripe} onClick={pay} className="bg-black text-white rounded p-3">{busy?'Processing…':'Pay and place order'}</button></div>
}
export default function MedusaCart(){
 const [cart,setCart]=useState<HttpTypes.StoreCart|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[clientSecret,setClientSecret]=useState(''),[order,setOrder]=useState('')
 const [address,setAddress]=useState({email:'',first_name:'',last_name:'',address_1:'',city:'',province:'',postal_code:''})
 useEffect(()=>{getPrintCart().then(setCart).catch(()=>setError('Unable to load your cart.'))},[])
 async function checkout(){if(!cart)return;setBusy(true);setError('');try{const {email,...shipping}=address;let updated=(await medusa.store.cart.update(cart.id,{email,shipping_address:{...shipping,country_code:'us'},billing_address:{...shipping,country_code:'us'}})).cart;const {shipping_options}=await medusa.store.fulfillment.listCartOptions({cart_id:cart.id});const option=shipping_options.find(o=>o.name?.startsWith('Standard'));if(!option)throw Error('Shipping unavailable');updated=(await medusa.store.cart.addShippingMethod(cart.id,{option_id:option.id})).cart;const {payment_collection}=await medusa.store.payment.initiatePaymentSession(updated,{provider_id:'pp_stripe_stripe'});const session=payment_collection.payment_sessions?.find(s=>s.provider_id==='pp_stripe_stripe');const secret=session?.data?.client_secret;if(typeof secret!=='string')throw Error('Payment unavailable');setCart(updated);setClientSecret(secret)}catch{setError('Unable to prepare checkout. Check your address and try again.')}finally{setBusy(false)}}
 async function remove(id:string){if(!cart)return;try{await medusa.store.cart.deleteLineItem(cart.id,id);setCart((await medusa.store.cart.retrieve(cart.id)).cart)}catch{setError('Unable to remove item')}}
 if(order)return <section className="max-w-3xl mx-auto p-8"><h1 className="text-2xl">Thank you — order received</h1><p>Order {order}</p><p>Your print configuration is saved. A digital proof is required before production.</p></section>
 return <section className="max-w-3xl mx-auto p-8 space-y-5"><h1 className="text-2xl font-semibold">Your print cart</h1>{error&&<p role="alert">{error}</p>}{!cart?<p>Loading…</p>:<>{cart.items?.map(item=><article key={item.id} className="border rounded p-4"><h2>{item.title}</h2><p>{String((item.metadata?.display as {summary?:string})?.summary||'Configured print job')}</p><p>${Number(item.unit_price).toFixed(2)}</p>{!clientSecret&&<button onClick={()=>remove(item.id)}>Remove</button>}</article>)}<p>Total: ${Number(cart.total).toFixed(2)}</p>{!cart.items?.length?<a href="/shop/stickers">Configure stickers</a>:clientSecret&&stripePromise?<Elements stripe={stripePromise} options={{clientSecret}}><Pay cart={cart} onComplete={setOrder}/></Elements>:<form className="space-y-3" onSubmit={e=>{e.preventDefault();void checkout()}}><h2>Delivery address</h2>{Object.keys(address).map(key=><label key={key} className="block capitalize">{key.replaceAll('_',' ')}<input className="border rounded block p-2 w-full" required type={key==='email'?'email':'text'} value={address[key as keyof typeof address]} onChange={e=>setAddress({...address,[key]:e.target.value})}/></label>)}<p>United States · local-test shipping rate $10; tax placeholder 0%.</p><button disabled={busy} className="bg-black text-white rounded p-3">{busy?'Preparing…':'Continue to payment'}</button></form>}</>}</section>
}
