'use client'
import {useEffect,useState} from 'react'
import {fetchPrintQuote,getPrintCart,medusa} from '@/lib/medusa'
export default function MedusaStickerCalculator(){
 const [config,setConfig]=useState({widthIn:2,heightIn:2,quantity:100,material:'standard',finish:'matte',rush:'standard'})
 const [total,setTotal]=useState<number|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 useEffect(()=>{const ctrl=new AbortController();setTotal(null);const t=setTimeout(()=>{fetchPrintQuote('sticker',config,ctrl.signal).then(q=>{setTotal(q.totalCents);setError('')}).catch(()=>{if(!ctrl.signal.aborted)setError('Choose a valid size and quantity.')})},200);return()=>{clearTimeout(t);ctrl.abort()}},[config])
 async function add(){setBusy(true);setError('');try{const {products}=await medusa.store.product.list({handle:'custom-stickers'});const product=products[0];const variant=product?.variants?.find(v=>v.title===config.material);if(!variant)throw Error('This option is unavailable');const cart=await getPrintCart();await medusa.client.fetch(`/store/carts/${cart.id}/print-items`,{method:'POST',body:{product_id:product.id,variant_id:variant.id,engine:'sticker',config}});window.location.href='/cart'}catch{setError('Unable to add this print job. Please try again.')}finally{setBusy(false)}}
 return <section className="rounded-xl border bg-white p-6 space-y-4"><h2 className="text-xl font-semibold">Configure your stickers</h2>{(['widthIn','heightIn','quantity'] as const).map(k=><label key={k} className="block">{k==='widthIn'?'Width (inches)':k==='heightIn'?'Height (inches)':'Printed quantity'}<input className="block border rounded p-2 w-full" type="number" min={k==='quantity'?50:.5} step={k==='quantity'?1:.125} value={config[k]} onChange={e=>setConfig({...config,[k]:Number(e.target.value)})}/></label>)}{(['material','finish','rush'] as const).map(k=><label key={k} className="block capitalize">{k}<select className="block border rounded p-2 w-full" value={config[k]} onChange={e=>setConfig({...config,[k]:e.target.value})}>{(k==='material'?['standard','holographic']:k==='finish'?['matte','gloss','laminate']:['standard','48hr','24hr']).map(v=><option key={v}>{v}</option>)}</select></label>)}<p aria-live="polite">{total===null?'Calculating…':`Print job: $${(total/100).toFixed(2)}`}</p>{error&&<p role="alert">{error}</p>}<button className="bg-black text-white p-3 rounded w-full" disabled={busy||total===null} onClick={add}>{busy?'Adding…':'Add to cart'}</button><p className="text-sm">Digital proof before production. Artwork can be supplied after checkout.</p></section>
}
