import { test, expect } from '@playwright/test'

for (const width of [390, 1440]) {
  test(`embroidery page quote with paired artwork at ${width}px`, async ({ page }) => {
    await page.setViewportSize({ width, height: 900 })
    let posted = ''
    await page.route('**/api/quote', async route => {
      posted = route.request().postData() ?? ''
      await route.fulfill({ status: 200, contentType: 'application/json', body: '{"success":true}' })
    })
    await page.goto('/services/apparel/embroidery')
    const form = page.getByLabel('Embroidery quote form')
    await expect(form.getByText('Step 1 of 3')).toBeVisible()
    await expect(form.getByText(/preferred brand/i)).toHaveCount(0)
    await expect(form.getByRole('button', { name: 'Continue' })).toBeDisabled()
    await form.getByLabel('Garment type *').selectOption('Hat')
    await form.getByLabel('Quantity *').fill('48')
    await form.getByLabel('Who supplies the garments? *').selectOption('Lettuce Print supplies garments')
    await form.getByRole('button', { name: 'Continue' }).click()
    await form.getByLabel('Number of locations *').selectOption('2')
    await form.getByLabel('Placement *').nth(0).fill('Hat front')
    await form.getByLabel('Approximate design size *').nth(0).fill('3 x 2 in')
    await form.getByLabel('Logo / artwork (optional)').nth(0).setInputFiles({ name: 'logo.pdf', mimeType: 'application/pdf', buffer: Buffer.from('%PDF-1.4\nqa test') })
    await form.getByRole('button', { name: 'Not sure — help me choose' }).nth(1).click()
    await form.getByRole('button', { name: 'Not sure — help me size it' }).nth(1).click()
    await expect(form.getByLabel('Placement *').nth(1)).toHaveValue('Not sure — help me choose')
    await expect(form.getByRole('button', { name: 'Continue' })).toBeEnabled()
    await form.getByRole('button', { name: 'Continue' }).click()
    await expect(form.getByText('Location 1: Hat front · 3 x 2 in · Artwork: logo.pdf')).toBeVisible()
    await form.getByLabel('Name *').fill('QA Test')
    await form.getByLabel('Email *').fill('qa@example.com')
    await form.getByLabel('Phone *').fill('3475550100')
    await form.getByLabel('In-Hands Date *').fill('2026-12-15')
    await form.getByLabel('Shipping ZIP code *').fill('11206')
    await form.getByRole('button', { name: 'Request embroidery quote' }).click()
    await expect(page.getByText('Your embroidery request is in.')).toBeVisible()
    expect(posted).toContain('"formType":"embroidery"')
    expect(posted).toContain('"artworkLocations":[1]')
    expect(posted).toContain('logo.pdf')
    expect(posted).toContain('Not sure — help me choose')
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  })
}

test('removing an embroidery location removes its artwork', async ({ page }) => {
  let posted = ''
  await page.route('**/api/quote', async route => { posted = route.request().postData() ?? ''; await route.fulfill({ status: 200, contentType: 'application/json', body: '{"success":true}' }) })
  await page.goto('/services/apparel/embroidery')
  const form = page.getByLabel('Embroidery quote form')
  await form.getByLabel('Garment type *').selectOption('Polo')
  await form.getByLabel('Quantity *').fill('20')
  await form.getByLabel('Who supplies the garments? *').selectOption('I supply garments')
  await form.getByRole('button', { name: 'Continue' }).click()
  await form.getByLabel('Number of locations *').selectOption('2')
  await form.getByLabel('Placement *').nth(0).fill('Chest')
  await form.getByLabel('Approximate design size *').nth(0).fill('2 in')
  await form.getByLabel('Placement *').nth(1).fill('Sleeve')
  await form.getByLabel('Approximate design size *').nth(1).fill('1 in')
  await form.getByLabel('Logo / artwork (optional)').nth(1).setInputFiles({ name: 'removed.pdf', mimeType: 'application/pdf', buffer: Buffer.from('%PDF-1.4\nqa test') })
  await form.getByLabel('Number of locations *').selectOption('1')
  await form.getByRole('button', { name: 'Continue' }).click()
  await form.getByLabel('Name *').fill('QA')
  await form.getByLabel('Email *').fill('qa@example.com')
  await form.getByLabel('Phone *').fill('3475550100')
  await form.getByLabel('In-Hands Date *').fill('2026-12-15')
  await form.getByLabel('Shipping ZIP code *').fill('11206')
  await form.getByRole('button', { name: 'Request embroidery quote' }).click()
  await expect(page.getByText('Your embroidery request is in.')).toBeVisible()
  expect(posted).not.toContain('removed.pdf')
  expect(posted).toContain('"artworkLocations":[]')
})
