import { test, expect } from '@playwright/test'

for (const viewport of [{ width: 390, height: 844 }, { width: 1440, height: 900 }]) {
  test(`screenprint location/color pairing ${viewport.width}px`, async ({ page }) => {
    await page.setViewportSize(viewport)
    let payload: Record<string, unknown> | undefined
    await page.route('**/api/quote', async route => {
      payload = route.request().postDataJSON()
      await route.fulfill({ status: 200, contentType: 'application/json', body: '{"success":true}' })
    })
    await page.goto('/get-quote')
    await page.getByRole('button', { name: /Screen Printing/ }).click()
    await page.getByRole('button', { name: /Continue/ }).click()
    const locationSelect = page.getByLabel(/Print locations/)
    const garmentSelect = page.getByLabel(/Garment type/)
    await garmentSelect.selectOption('T-shirt')
    await page.getByPlaceholder('e.g. 48').fill('72')
    await expect(locationSelect).toBeVisible()
    await locationSelect.selectOption('3')
    await expect(page.getByRole('group', { name: 'Location 3' })).toBeVisible()
    await expect(page.getByRole('button', { name: /Continue/ })).toBeDisabled()
    await page.locator('#location1Name').fill('Front chest')
    await page.locator('#location1Colors').selectOption('2')
    await page.locator('#location2Name').fill('Full back')
    await page.locator('#location2Colors').selectOption('1')
    await page.locator('#location3Colors').selectOption('5+')
    await expect(page.getByRole('button', { name: /Continue/ })).toBeEnabled()
    await locationSelect.selectOption('2')
    await expect(page.getByRole('group', { name: 'Location 3' })).toHaveCount(0)
    await locationSelect.selectOption('3')
    await expect(page.locator('#location1Colors')).toHaveValue('2')
    await expect(page.locator('#location2Colors')).toHaveValue('1')
    await expect(page.locator('#location3Colors')).toHaveValue('')
    await page.locator('#location3Name').fill('Sleeve')
    await page.locator('#location3Colors').selectOption('3')
    await page.getByRole('button', { name: /Continue/ }).click()
    await page.getByRole('button', { name: /Back/ }).click()
    await expect(page.locator('#location3Name')).toHaveValue('Sleeve')
    await page.getByRole('button', { name: /Continue/ }).click()
    await page.getByRole('button', { name: /Flexible/ }).click()
    await page.getByRole('button', { name: /Continue/ }).click()
    await page.getByPlaceholder('Your name').fill('QA Test')
    await page.getByPlaceholder('your@email.com').fill('qa@example.com')
    await page.getByRole('button', { name: /Submit Request/ }).click()
    await expect(page.getByRole('heading', { name: 'We got it!' })).toBeVisible()
    expect(payload?.service).toBe('Screen Printing')
    expect(payload?.projectDetails).toMatchObject({ printLocations: '3', location1Name: 'Front chest', location1Colors: '2', location2Name: 'Full back', location2Colors: '1', location3Name: 'Sleeve', location3Colors: '3' })
    expect(Object.keys(payload?.projectDetails as object)).not.toContain('colors')
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  })
}

test('reducing location count removes inactive answers from submission', async ({ page }) => {
  let details: Record<string, string> | undefined
  await page.route('**/api/quote', async route => {
    details = route.request().postDataJSON().projectDetails
    await route.fulfill({ status: 200, contentType: 'application/json', body: '{"success":true}' })
  })
  await page.goto('/get-quote')
  await page.getByRole('button', { name: /Screen Printing/ }).click()
  await page.getByRole('button', { name: /Continue/ }).click()
  await page.getByLabel(/Garment type/).selectOption('T-shirt')
  await page.getByPlaceholder('e.g. 48').fill('48')
  await page.getByLabel(/Print locations/).selectOption('3')
  await page.locator('#location1Colors').selectOption('2')
  await page.locator('#location2Colors').selectOption('1')
  await page.locator('#location3Name').fill('Sleeve')
  await page.locator('#location3Colors').selectOption('4')
  await page.getByLabel(/Print locations/).selectOption('2')
  await page.getByRole('button', { name: /Continue/ }).click()
  await page.getByRole('button', { name: /Flexible/ }).click()
  await page.getByRole('button', { name: /Continue/ }).click()
  await page.getByPlaceholder('Your name').fill('QA Test')
  await page.getByPlaceholder('your@email.com').fill('qa@example.com')
  await page.getByRole('button', { name: /Submit Request/ }).click()
  await expect(page.getByRole('heading', { name: 'We got it!' })).toBeVisible()
  expect(details?.printLocations).toBe('2')
  expect(details?.location1Colors).toBe('2')
  expect(details?.location2Colors).toBe('1')
  expect(Object.keys(details ?? {}).some(key => key.startsWith('location3'))).toBe(false)
})

test('generic quote and roll-label preselection remain usable', async ({ page }) => {
  await page.goto('/get-quote?service=stickers-labels&product=roll-labels')
  await expect(page.getByText('Roll labels selected.')).toBeVisible()
  await page.getByRole('button', { name: /Continue/ }).click()
  await expect(page.getByLabel(/Material/)).toHaveValue('Not sure')
  await expect(page.getByLabel(/Anything else we should know/)).toContainText('Custom roll labels')
  await expect(page.getByRole('button', { name: /Continue/ })).toBeDisabled()
  await page.getByLabel(/Size/).fill('3 × 3 in')
  await page.getByLabel(/Quantity/).fill('500')
  await expect(page.getByRole('button', { name: /Continue/ })).toBeEnabled()
})

for (const viewport of [{ width: 390, height: 844 }, { width: 1440, height: 900 }]) {
  test(`embedded screenprint page form ${viewport.width}px`, async ({ page }) => {
    await page.setViewportSize(viewport)
    let payload: Record<string, unknown> | undefined
    await page.route('**/api/quote', async route => {
      payload = route.request().postDataJSON()
      await route.fulfill({ status: 200, contentType: 'application/json', body: '{"success":true}' })
    })
    await page.goto('/services/apparel/screenprint')
    const formSection = page.getByRole('region', { name: 'Request a screen printing quote' })
    await expect(formSection.getByRole('heading', { name: 'Tell us about the project' })).toBeVisible()
    await expect(formSection.getByRole('button', { name: /Screen Printing/ })).toHaveCount(0)
    await expect(formSection.getByRole('button', { name: /Back/ })).toHaveCount(0)
    await formSection.getByLabel(/Garment type/).selectOption('T-shirt')
    await formSection.getByPlaceholder('e.g. 48').fill('72')
    await formSection.getByLabel(/Print locations/).selectOption('2')
    await expect(formSection.getByRole('button', { name: /Continue/ })).toBeDisabled()
    await formSection.locator('#location1Name').fill('Front chest')
    await formSection.locator('#location1Colors').selectOption('2')
    await formSection.locator('#location2Name').fill('Full back')
    await formSection.locator('#location2Colors').selectOption('1')
    await formSection.getByRole('button', { name: /Continue/ }).click()
    await formSection.getByRole('button', { name: /Back/ }).click()
    await expect(formSection.locator('#location1Colors')).toHaveValue('2')
    await formSection.getByRole('button', { name: /Continue/ }).click()
    await formSection.getByRole('button', { name: /Flexible/ }).click()
    await formSection.getByRole('button', { name: /Continue/ }).click()
    await formSection.getByPlaceholder('Your name').fill('QA Test')
    await formSection.getByPlaceholder('your@email.com').fill('qa@example.com')
    await formSection.getByRole('button', { name: /Submit Request/ }).click()
    await expect(formSection.getByRole('heading', { name: 'We got it!' })).toBeVisible()
    expect(payload?.service).toBe('Screen Printing')
    expect(payload?.projectDetails).toMatchObject({ printLocations: '2', location1Name: 'Front chest', location1Colors: '2', location2Name: 'Full back', location2Colors: '1' })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  })
}

test('other apparel service keeps generic quote CTA', async ({ page }) => {
  await page.goto('/services/apparel/embroidery')
  await expect(page.getByRole('link', { name: 'Request a Quote' })).toHaveAttribute('href', '/get-quote')
  await expect(page.getByRole('heading', { name: 'Tell us about the project' })).toHaveCount(0)
})
